### PR TITLE
Emit l2BlockNumber in the Resolved event

### PR DESCRIPTION
**Pull request by boyuan-chen**
:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

To reduce the number of RPC calls needed to retrieve the `l2BlockNumber` submitted with the state root in the game, I have added the `l2BlockNumber` and rootClaim to the event.

This allows us to retrieve all necessary information for the withdrawal from our subgraph rather than making RPC calls to get the `l2BlockNumber`.

Here is how the current implementation works: https://github.com/bobanetwork/graphql-utils/pull/9/files Basically, we need to perform a for loop to find the game where its `l2BlockNumber` is larger than the target value, and the previous game’s `l2BlockNumber` is smaller than the target value.
## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Add new fields
- Add tests

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

The tests are added

### CODE REVIEW

**Review by wsdt — APPROVED** [review]

**Review by mmontour1306 — APPROVED** [review]

**Comment by boyuan-chen** [comment]
The new `FaultDisputeGame` is deployed to `0x5D20776Fb8D91181873F210bFb89eAA694217c0b` and is set as the implementation contract for game type 0 in our `DisputeGameFactoryProxy`.

**Comment by boyuan-chen** [comment]
I will try to push this to the upstream.

**Comment by boyuan-chen** [comment]
I have followed their contribution rule and created a Github issue for the discussion. https://github.com/ethereum-optimism/optimism/issues/11409

**Review by souhaillM — APPROVED** [review]
LGTM

**Pull request merged**
